tasks:
  - name: Download JAR Dependencies
    init: |
      echo "Downloading JAR dependencies..."
      mkdir -p jars
      curl -L -o jars/hadoop-aws-3.3.4.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar
      curl -L -o jars/aws-java-sdk-bundle-1.12.262.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar
      echo "JAR dependencies downloaded successfully!"

  - name: Start Services
    init: |
      echo "Starting services..."
      docker-compose up -d
      echo "Waiting for services to become ready..."
      gp ports await 9001
      gp ports await 8080
      gp ports await 8181
      gp ports await 8888
      echo "Services started!"
      echo "Jupyter Notebook: $(gp url 8888)"
      echo "MinIO Console:    $(gp url 9001) (admin/password)"
      echo "Spark UI:         $(gp url 8080)"
      echo "Iceberg REST:     $(gp url 8181)"
      echo ""
      echo "Once the environment finishes warming up, you'll get a direct link to the demo notebook below."
    command: |
      # Follow logs for debugging
      docker-compose logs -f & 
      sleep 3
      wait

  - name: Print Notebook Link
    init: |
      echo "Preparing the notebook link..."
    command: |
      gp ports await 8888
      BASE="$(gp url 8888)"
      NOTEBOOK_PATH="/notebooks/iceberg_pii_deletion_demo.ipynb"

      LINK="${BASE}${NOTEBOOK_PATH}"

      echo ""
      echo "======================================================================"
      echo " ✅ Your environment is getting ready."
      echo ""
      echo " 👉 Open the notebook in your browser here:"
      echo ""
      echo "    ${LINK}"
      echo ""
      echo " ⏳ First start can take a few minutes. If it 404s, refresh in a bit."
      echo "======================================================================"
      echo ""
